### ISSUE TITLE
Video's on macOS

### ISSUE THREAD

**Issue by bblfish** [nostur-com/nostur-ios-public#1]
I noticed the YouTube video does not have a picture for Nostur 1.5.0 (155) on macOS Ventura 13.5

Also I could not load the below screenshot from Photo.app or drag and drop it into the app on macos... (I had to use a different app).  Otherwise it seems pretty useable...

(I also tried to compile it, but it looks like I need a developer certificate or something, and I am a Scala programmer rather than an iOS one)
![screen shot for Nostur 1.5.0 (155) on macOS Ventura 13.5](https://m.primal.net/HIxp.png)
[reported on #nostr](https://primal.net/e/note172mtfa7x5vgky30trpufnqmxlqtx8nayrlky6d60d6cwqz086krsh4asc2)

Just in case it is relevant, I am on Safari Version 17.0 (18616.1.24.11.5, 18616)

**Comment by fabianfabian** [comment]
YouTube video thumbnail should be fixed with [#1e91137525438078fadc51f21c1840c543b23130](https://github.com/nostur-com/nostur-ios-public/commit/1e91137525438078fadc51f21c1840c543b23130)

**Comment by bblfish** [comment]
yes, that works now:
<img width="904" alt="Screenshot 2023-08-20 at 12 18 07" src="https://github.com/nostur-com/nostur-ios-public/assets/124506/7c0860ab-cb06-4d64-bd41-ae7c3d89e354">
