### ISSUE TITLE
Image files not loading correct with nostrcheck server

### ISSUE THREAD

**Issue by quentintaranpino** [nostur-com/nostur-ios-public#14]
The problem can be reproduced uploading a file from nostur 1.12.0 (build: 267) to a NIP96 server using nostrcheck-server engine.

The file uploads correctly but the note is created in a way that the server rejects the request and returns "file not found".

I have tried from Coracle, which also has NIP96 support and it uploads fine. 

Example:

**NOSTUR** (not loading):

{"content":"Test\nhttps://nostrcheck.me/media/quentin/d4510a04119dce951790fcb73c6dbf2c054c517a438ce5aa8cbd0ed26630e773.webp","created_at":1707673723,"id":"41d31039df32ffa7a92b59215979e082d048c724b0fca2e7dd3f9cfbf636da8b","kind":1,"pubkey":"89e14be49ed0073da83b678279cd29ba5ad86cf000b6a3d1a4c3dc4aa4fdd02c","sig":"df5c462196f9af4fc8d3282e09f74664a7a7e2716a0a12d36f2190eb29c6f86b2a43e329d39e0cbc3e08b3ef9603a103f993429b5c57df9651006a92235eeeb3","tags":[["imeta","url https://nostrcheck.me/media/quentin/d4510a04119dce951790fcb73c6dbf2c054c517a438ce5aa8cbd0ed26630e773.webp","dim 480x960","sha256 c6ea92eede82ffd9257bde4ef8a1554b14ca6305656bb5123eaffff7a36b298f"],["client","Nostur","31990:9be0be0fc079548233231614e4e1efc9f28b0db398011efeecf05fe570e5dd33:1685868693432"]]}

The image:
https://nostrcheck.me/media/quentin/d4510a04119dce951790fcb73c6dbf2c054c517a438ce5aa8cbd0ed26630e773.webp
(exist but not loading inside the note)

The event:

nostr:nevent1qydhwumn8ghj7un9d3shjtn0wfskuem9wp5kcmpwv3jhvtcpr9mhxue69uhhwetvvdhk6efwdehhxarj9emkjmn99uq3xamnwvaz7tm0venxx6rpd9hzuur4vghszymhwden5te0wp6hyurvv4cxzeewv4ej7qg4waehxw309aex2mrp0yhxgctdw4eju6t09uq3samnwvaz7tmjv4kxz7fwwpkx2cnnw3ezucm0d5hszxnhwden5te0dehhxarj9e6xsetnv9kk2cmpwshxjme0qyd8wumn8ghj7un9d3shjtnwdaehgunrdpjkx6ewd4jj7qg3waehxw309ahx7um5wgh8w6twv5hsz9mhwden5te0wfjkccte9ehx7um5wghxyctwvshszrnhwden5te0dehhxtnvdakz7qg3waehxw309ucngvpwvcmh5tnfduhszxnhwden5te0wpuhyctdd9jzuenfv96x5ctx9e3k7mf0qyf8wumn8ghj7ur4wfcxcetsv9njuetnqy28wumn8ghj7un9d3shjtnyv9kh2uewd9hsz9nhwden5te0wfjkccte9ehx7um5wghxyctwvsq3xamnwvaz7tmjv4kxz7tpvfkx2tn0wfnszyrhwden5te0dehhxarj9emkjmn9qqsyr5cs880n9la84y44jg2e08sg95zgcujtpl9zulwnl88m7cmd4zck2sg8x

**CORACLE** (working):

{"content":"test\nhttps://nostrcheck.me/media/quentin/c6ea92eede82ffd9257bde4ef8a1554b14ca6305656bb5123eaffff7a36b298f.webp","created_at":1707674107,"id":"2769057c063869e65e5103822c43d95c978966e69209cb19beda31ced4be4d56","kind":1,"pubkey":"89e14be49ed0073da83b678279cd29ba5ad86cf000b6a3d1a4c3dc4aa4fdd02c","sig":"9870a0273d4f26584db5dc05d94ad53f27f28fed7e1827a8ebf7913983f8a709fbff8a26d26addafb63fe645ffb01df6fae20b67c0ad9f938c5af8e2e2692536","tags":[["imeta","url https://nostrcheck.me/media/quentin/c6ea92eede82ffd9257bde4ef8a1554b14ca6305656bb5123eaffff7a36b298f.webp","m image/webp","x 7a1d682a2f1ec0aeb25d7c414e5829663c678635eb38f4f1962f823829f80cd0","ox c6ea92eede82ffd9257bde4ef8a1554b14ca6305656bb5123eaffff7a36b298f","size 28576","dim 480x960","blurhash UCA+m]^a}+=?xLI:NFWCEKRqEKRpEINLN2Rp"]]}

The image:
https://nostrcheck.me/media/quentin/c6ea92eede82ffd9257bde4ef8a1554b14ca6305656bb5123eaffff7a36b298f.webp

The event:

{"content":"test\nhttps://nostrcheck.me/media/quentin/c6ea92eede82ffd9257bde4ef8a1554b14ca6305656bb5123eaffff7a36b298f.webp","created_at":1707674107,"id":"2769057c063869e65e5103822c43d95c978966e69209cb19beda31ced4be4d56","kind":1,"pubkey":"89e14be49ed0073da83b678279cd29ba5ad86cf000b6a3d1a4c3dc4aa4fdd02c","sig":"9870a0273d4f26584db5dc05d94ad53f27f28fed7e1827a8ebf7913983f8a709fbff8a26d26addafb63fe645ffb01df6fae20b67c0ad9f938c5af8e2e2692536","tags":[["imeta","url https://nostrcheck.me/media/quentin/c6ea92eede82ffd9257bde4ef8a1554b14ca6305656bb5123eaffff7a36b298f.webp","m image/webp","x 7a1d682a2f1ec0aeb25d7c414e5829663c678635eb38f4f1962f823829f80cd0","ox c6ea92eede82ffd9257bde4ef8a1554b14ca6305656bb5123eaffff7a36b298f","size 28576","dim 480x960","blurhash UCA+m]^a}+=?xLI:NFWCEKRqEKRpEINLN2Rp"]]}

I'm not sure if it's a problem on the server side, so I apologise in advance if it's just me.  

If you need more information I can run more tests

**Comment by quentintaranpino** [comment]
It can be closed, it was cloudflare and its cache 😅

**Comment by fabianfabian** [comment]
👍
