### ISSUE TITLE
Add additional view copy npub avenues

### ISSUE THREAD

**Issue by alltheseas** [nostur-com/nostur-ios-public#21]
Sometimes it is useful to be able to view and grab a npub without having to go to a user's profile -> ellipsis menu.

Consider adding a way to view, and copy npub in the following views

![image](https://github.com/user-attachments/assets/219e9372-b2db-4158-8100-a267ae763e1f)

![image](https://github.com/user-attachments/assets/851c8176-0572-41f3-8380-1cadcce4124e)

**Comment by fabianfabian** [comment]
added in https://github.com/nostur-com/nostur-ios-public/commit/75a7fac9ab3ce98979a71dcd1c4a4f7e609b7ea7
