### ISSUE TITLE
Local profile never updates

### ISSUE THREAD

**Issue by badonyx** [nostur-com/nostur-ios-public#4]
Profile data never updates in sidebar, account switcher, or Edit Profile. When I view my profile I see the current data but in Edit Profile it is very outdated. 

I have only edited my profile from other clients, so my guess is it keeps a local copy of the profile data and that copy is only getting updated with local profile edits.

**Comment by badonyx** [comment]
Local profile data still not updated on 1.9 (205)

**Comment by fabianfabian** [comment]
Before it didn't update the local account from relay events at all, now it will when it sees a new profile update. It should resolve itself eventually, except when you never update your profile.

**Comment by badonyx** [comment]
I updated my profile externally and then opened Nostur and it's updated now. Thanks!
