### ISSUE TITLE
Selectable text

### ISSUE THREAD

**Issue by badonyx** [nostur-com/nostur-ios-public#7]
Text should be selectable to allow for processing with system services like dictionary and translation.

This is from Damus for example, comparing the app's LibreTranslate service to system translation from text selection.

![image](https://github.com/nostur-com/nostur-ios-public/assets/110633279/dbc8350a-1654-4f2c-a0f4-c493927bdaf1)

**Comment by fabianfabian** [comment]
Fixed with 925f0782e518be343301214ed131a47e5cae455f
